-- Window Resolution
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

-- Virtual Resolution
VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144

CAMERA_SCROLL_SPEED = 50
MAP_WIDTH = 100
MAP_HEIGHT = 10

DEFAULT_GROUND_LEVEL = 6
SAFE_ZONE_WIDTH = 5

SPAWN_PILLAR_CHANCE = 8
PILLAR_HEIGHT = 2
SPAWN_PILLAR_BUSH_CHANCE = 6

SPAWN_CHASM_CHANCE = 8
CHASM_HEIGHT = 1

SPAWN_WATER_CHANCE = 8
SPAWN_FLOAT_BUSH_CHANCE = 6

SPAWN_GROUND_BUSH_CHANCE = 8

SPAWN_GEM_CHANCE = 16

-- Constants related to Tiles
TILE_SIZE = 16

-- size's are in terms of TILE_SIZE
TILE_SET_WIDTH = 5
TILE_SET_HEIGHT = 4

TILE_SETS_WIDE = 6
TILE_SETS_TALL = 10

-- number of topper sets in sheet
TOPPER_SETS_WIDE = 6
TOPPER_SETS_TALL = 18

-- total number of topper and tile sets
TOPPER_SETS = TOPPER_SETS_WIDE * TOPPER_SETS_TALL
TILE_SETS = TILE_SETS_WIDE * TILE_SETS_TALL

WATER_TOP = 1
WATER_BOTTOM = 2

GEMS = {
    5, 6, 7, 8
}

BUSH_IDS = {
    1, 2, 5, 6, 7
}

COIN_IDS = {
    1, 2, 3
}


-- Constants related to player
PLAYER_WALK_SPEED = 53
PLAYER_JUMP_VELOCITY = -140


LEFT = -1
RIGHT = 1
